<?php

namespace ContainerZeCxUVt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8ON5BGEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8ON5BGE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8ON5BGE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cache' => ['privates', 'cache.app.taggable', 'getCache_App_TaggableService', true],
            'rencontre' => ['privates', '.errored..service_locator.8ON5BGE.App\\Entity\\Rencontre', NULL, 'Cannot autowire service ".service_locator.8ON5BGE": it references class "App\\Entity\\Rencontre" but no such service exists.'],
            'serializer' => ['services', 'jms_serializer', 'getJmsSerializerService', true],
        ], [
            'cache' => '?',
            'rencontre' => 'App\\Entity\\Rencontre',
            'serializer' => '?',
        ]);
    }
}
